### ISSUE TITLE
Fix Macro line graph

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#157]
The line graph that tracks macroinvertebrates over time is broken.

Firefox:
![macro_time2](https://cloud.githubusercontent.com/assets/6801364/18964827/6781b776-862f-11e6-806d-d678e7f9d87e.png)

Google:
![macro_time_google](https://cloud.githubusercontent.com/assets/6801364/18964838/704585ea-862f-11e6-9383-45ffe04e4e4b.png)

@alxngyn @LyonesGamer 

Let's try to figure this out before the meeting with Renee next week (Tuesday @ 12:30).

**Comment by alxngyn** [comment]
@athai is this on develop? If this is, this is what I found:
* some data from datasheets don't have matching sites so I ran into this:
 * ` DoesNotExist: Site matching query does not exist. *
* some sites don't have data so the charts show the X&Y axis lines but nothing else (I think this is what @athai ran into)
* `http://localhost:8000/streamwebs/sites/greasy-creek/macros/` is a good one i found that has data and it shows up.

**Comment by LyonesGamer** [comment]
`window.data_time = {"1440430800.0": {"Sensitive": 0, "Somewhat Sensitive": 0, "Tolerant": 0}, "1440428700.0": {"Sensitive": 0, "Somewhat Sensitive": 0, "Tolerant": 0}, "1440430260.0": {"Sensitive": 0, "Somewhat Sensitive": 0, "Tolerant": 0}, "1440510420.0": {"Sensitive": 0, "Somewhat Sensitive": 0, "Tolerant": 0}};`

Well...I'm not sure exactly what the cause is, but I found the problem.

**Comment by alxngyn** [comment]
@LyonesGamer 
https://github.com/osuosl/streamwebs/blob/develop/streamwebs_frontend/streamwebs/views.py#L203
I couldn't find any corresponding get_totals() function in the macro class. 
Did it get removed?

**Comment by LyonesGamer** [comment]
@alxngyn 

https://github.com/osuosl/streamwebs/blob/develop/streamwebs_frontend/streamwebs/models.py#L738-L743

**Comment by athai** [comment]
Fixed by #164.
