### ISSUE TITLE
Zone creation should be required

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#210]
If the user doesn't fill out the zones section of the Riparian Transect data sheet, form submission should fail. Currently, StreamWebs will create a new transect object with no associated zones (which is correct behavior, to be fair). Should we set a limitation that rejects transect creation entirely if it has no associated zones?

**Comment by subnomo** [comment]
If I'm understanding correctly, Riparian Transect data sheets without zone data are essentially useless. So yes, I think we should enforce entering data for at least one of the zones.

**Comment by leian7** [comment]
^^^ agree. I thought that blank zones would still be created but with number values of 0, but this isn't the case and like @subnomo said, blank zones are useless anyway.

**Comment by leian7** [comment]
The plan after discussing with @athai: for a riparian transect data sheet, at least one zone must have at least one number value (conifers, hardwoods or shrubs) that is greater than 0. Otherwise the user should be restricted from submitting the sheet.

**Comment by leian7** [comment]
https://docs.djangoproject.com/en/1.10/topics/forms/formsets/#formset-validation
"The formset is smart enough to ignore extra forms that were not changed."
Since the forms in the formset have default values of 0, if the user chooses to ignore a few zones, the formset will ignore those forms and will never create those zone objects. This complicates things further when trying to assign zone numbers since there would then be less than 5 zones, and our current implementation is designed to assume five zones and simply loop through them to store and display their respective data. Plus, the zone model's zone_num variable never gets set when processing a new zone object through a form?... Looks like it's only being correctly used in the import script for existing riparian transect data.
Still working on this:
- [ ] Enforce creation of 5 zones per valid transect given that at least one zone has at least one number that isn't 0 (all zones having all 0s is still silly). 
- [ ] Above should automatically solve the problem, but ensure that zones are enumerated correctly with the zone model's zone_num attribute.
