### ISSUE TITLE
User migrations/send emails to active users

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#268]
Eventually, we'll need to fully migrate (active) users from the old StreamWebs site to the new one. Since we can't migrate their passwords as well, we need to create a script that will auto-generate random temporary passwords for each account and email them out to users.

Issue #267 needs to be completed alongside, or before, this one.

**Comment by alxngyn** [comment]
I feel like mass emailing users their passwords is a bad idea.
Let's just generate random passwords for all users and have a banner on the login page saying something like "With the new update, please reset your password"

**Comment by alxngyn** [comment]
- Look at django email system
- batch email users
- filter out users who haven't logged in in X years

**Comment by Kennric** [comment]
@alxngyn I am not sure we need to import users, since the user object isn't really tied to any other objects.

 One solution may be just to email them a link to the registration form, and pre-fill that form with their name/email/school so that all they need to do is enter a password. We'll need to modify that form to get name/email/school from GET request params. This should really filter out anyone who isn't actually using the site, since accounts won't even be created unless they follow the link and register.

Second, and probably better option is a password reset feature. Import the user accounts with a random password that can be reset via a standard "I forgot my email" type of function. The other advantage of this is that we'll have password resets for general use. Django has this built in: 

https://docs.djangoproject.com/en/1.11/topics/auth/default/#django.contrib.auth.views.PasswordResetView

Then we email them after import with a link to the reset password form.

**Comment by alxngyn** [comment]
@Kennric I believe all current datasheets have a user tied to them since inception. This is the only way to organize the data sheets by school since the old streamwebs tied the user to the school.

I agree with everything else though. We should implement the django passwordResetView asap.

**Comment by hertelc** [comment]
What is the status on this please? I think High Priority items should get an update on a daily basis until we get released. @baileysingleton @JerryPeng0112
