### ISSUE TITLE
Add photo points fix

### ISSUE THREAD

**Issue by JerryPeng0112** [osuosl/streamwebs#347]
1. Figure out what map datum is
2. Add measurement to: Distance from camera points, camera height
3. Figure out required field (should only require one)
4. Add association with school

**Comment by baileysingleton** [comment]
Map Datum Field - Is this a field that is supposed to be filled in by the map widget?  This is a free form text field.


![pp1](https://user-images.githubusercontent.com/26613813/29144788-22efa8ac-7d0f-11e7-8d34-fc52e43603af.png)

"Distance from camera point" Field has no measurement type (meters?  feet?  inches?)
"Camera Height" Field has no measurement type (meters?  feet?  inches?)

![pp2](https://user-images.githubusercontent.com/26613813/29144791-266e249a-7d0f-11e7-90ec-96835b769f29.png)


You are required to fill out information for three photos even if you only have one or two before the page will be submitted.  There is no indication that required fields are missing other than the page will not submit.

(No photo to show this)

There is no School field required when adding a photo point.  Results show under the site as "No School Associated"
![pp3](https://user-images.githubusercontent.com/26613813/29144798-2a88460a-7d0f-11e7-95de-f2ec20abf1dd.png)

Next Page function not working.  Submitted enough data to fill one page including two photo point items that appear under the “No School Associated” label, but when trying to go to the next page using the ‘>>’ arrows nothing happens.

![Uploading pp4.png…]()

**Comment by leian7** [comment]
@JerryPeng0112 @baileysingleton Map datums: https://www.maptools.com/tutorials/map_datum

@baileysingleton There seems to be some misunderstanding about the photo point monitoring data sheet, especially in regards to the minimum-3 "photos" thing. Rather than adding a "new photo point", you are actually adding a new "camera point." Each camera point, in turn, has at least three photo points (photo POINTS, not "photos"). And each photo point in turn can have an unlimited number of photos. Take a look at the descriptions for #60 and #151 for more details, and double check the urls file to make sure you're aware of how many views there are for each component of photo point monitoring. 

Re: the 3-photo point minimum: I think I have confirmed this with Renee before. My understanding is that it is important for a new camera point to start off with at least three photo points-- this is how the original data sheet (pdf version) is structured, and having less than three photo points probably isn't enough data to establish a new camera point. 

Anyway, as you can see, this data sheet is confusing-- if you haven't already, make sure you google 'photo point monitoring' just to get a better sense of what it entails out in the field. You can also double check with Renee, who might put you in touch with a teacher  (Bessie, I think) who uses the photo point monitoring data sheet frequently. I would forward you a direct correspondence that we had myself, but my OSL email account is deactivated. 

Let me know also if you have any questions for me.

**Comment by JerryPeng0112** [comment]
Ok, thank you
I didn't really get the format of the datasheets, and Renee sent the email with attachments of 2 word documents on what they think needs to be fixed and the photopoints issue was one of them, as you can see on the pictures attached above. So I'll make sure I send an email to confirm with Renee.
Btw, have you gotten the email from Lance, if not I can forward it to you
@leian7

**Comment by baileysingleton** [comment]
@leian7 Hey Annie, I'm working on cleaning up this view. I'm a little confused about how users are supposed to add unlimited photos to each photo point. After creating a datasheet, it shows me 3 photo points, with one photo on each, but no way to add more photos. 

Is this functionality already implemented, or is it something that we need to make happen?

thanks

**Comment by leian7** [comment]
@baileysingleton Hi Bailey, I am pretty sure you can click on one of those photo points to get to the individual view for that photo point. There should then be an upload button on that page where you can add and submit more photos, one at a time. Hope that helps-- if you need more info, let me know and I can help investigate.

**Comment by baileysingleton** [comment]
@leian7 Yep! You're totally right, thanks :)

**Comment by baileysingleton** [comment]
@leian7 One more question, are there only three possible datums they can choose from? If so, I would just turn that field into radio buttons.

**Comment by leian7** [comment]
@baileysingleton Yeah, there are "three most common", so that sounds reasonable... I would double check with Renee though.
