### ISSUE TITLE
add macro

### ISSUE THREAD

**Issue by JerryPeng0112** [osuosl/streamwebs#350]
1. percent EPT as an input field 
2. Change "Sensitive/Intolerant" to "Sensitive"

**Comment by baileysingleton** [comment]
Displayed results show "Percent EPT" and "Water Quality" fields but there is no opportunity on the survey form to enter this data.

![macro](https://user-images.githubusercontent.com/26613813/29145119-955a934c-7d10-11e7-9c6f-7c8bdfbd225a.png)

**Comment by leian7** [comment]
@JerryPeng0112 @baileysingleton Percent EPT and Water quality don't show up as fillable fields because they are automatically calculated based on the bug totals the user provides. See the original datasheet pdf for details on how the calculations are done. If you have questions or would like to be linked to a relevant PR, just let me know.

**Comment by baileysingleton** [comment]
@leian7 Thanks! We're going to leave it for now and we'll ask the clients about it.
