### ISSUE TITLE
Water Quality Page Required Fields

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#434]
I was able to save a Water Quality Data sheet without really putting in any water quality data... expected??  What are the required fields here?

Attaching a screenshot of the water quality report I was able to create with minimal information:

![waterqualityreport1](https://user-images.githubusercontent.com/20323475/31028168-dee0f3ee-a501-11e7-8675-3a80fb777bc8.jpg)

**Comment by hertelc** [comment]
@rensmere  Can you help with what the required fields are for the Water Quality report?

**Comment by rensmere** [comment]
In response to required fields, here is what I sent to students in August in response to their question:


  1.  What fields are required for each datasheets? We are very confused about some fields since we are not sure if they are required so we think it would be best if you can clarify.

Required fields for all datasheets: time, date, school (collected by who)
I believe that in the new site things are still graphed using time but if not time doesn’t have to be a required field.

Here are additional required fields on other datasheets or none if no additional:
·         Water quality: units (C or F)
·         Riparian and Aquatic Survey: none
·         Canopy Cover: none
·         Riparian Transect: none
·         Soil Survey: landscape position, cover type, land use, distance from stream
·         Photopoint: compass bearing
·         Streamflow: time, date, school (collected by who), width, depth, velocity

**Comment by hertelc** [comment]
Thank you!  This answers my questions.

**Comment by hertelc** [comment]
@baileysingleton, The Streamflow page appears to be missing?  I see it in the printable datasheets, but not the online ones.  Can you check this out?  Thanks!

**Comment by rensmere** [comment]
There are three pages that were eliminated in the rebuild:

·         Streamflow

·         Invasive Species

·         Pebble count

The datasheets still exist but maybe we shouldn’t have them on the new site as it could be confusing?

--
Renee O'Neill
Programs Coordinator
The Science and Math Investigative Learning Experiences (SMILE) Program and
Oregon Sea Grant StreamWebs Program
Oregon State University
(541) 737-5675 or (541) 737-2747
http://smile.oregonstate.edu<http://smile.oregonstate.edu/>
http://streamwebs.org<http://streamwebs.org/>

**Comment by hertelc** [comment]
I’m happy we aren’t missing  a page!

I personally don’t see a problem with having the printouts online.  Maybe add a note that it is paper only or something… ?   I was just concerned because of the required fields listed for Streamflow.

CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu

**Comment by rensmere** [comment]
Yeah, let’s keep them.  They are still useful even if they cant enter them into the database.  If it is easy to add a note next to those datasheets that would be great.

Renee

**Comment by hertelc** [comment]
Closing out this ticket in favor of #452 which covers adding the text about paper only.
