### ISSUE TITLE
Pebble Count data missing

### ISSUE THREAD

**Issue by ramereth** [osuosl/streamwebs#505]
I discovered that we haven't implemented Pebble Count data into the application. There seems to be about 32 data entries for this data type like this one: http://drupal.streamwebs.org/data/pebble-count/west-olalla-creek/04-14-2017. I'm not sure whether this was intentional or on the to do list. Here is what the input form looks like: http://drupal.streamwebs.org/node/add/data-pebble-count

@rensmere any insight on this? Does it need to be implemented?

**Comment by rensmere** [comment]
Pebble count does not need to be implemented.

On Oct 25, 2017, at 9:24 AM, Lance Albertson <notifications@github.com<mailto:notifications@github.com>> wrote:


I discovered that we haven't implemented Pebble Count data into the application. There seems to be about 32 data entries for this data type like this one: http://drupal.streamwebs.org/data/pebble-count/west-olalla-creek/04-14-2017. I'm not sure whether this was intentional or on the to do list. Here is what the input form looks like: http://drupal.streamwebs.org/node/add/data-pebble-count

@rensmere<https://github.com/rensmere> any insight on this? Does it need to be implemented?
