### ISSUE TITLE
Stream Flow data missing

### ISSUE THREAD

**Issue by ramereth** [osuosl/streamwebs#506]
I discovered that we haven't implemented Stream Flow data into the application. There seems to be about 62 data entries for this data type like this one: http://drupal.streamwebs.org/data/stream-flow/west-olalla-creek/05-30-2017. I'm not sure whether this was intentional or on the to do list. Here is what the input form looks like: http://drupal.streamwebs.org/node/add/data-stream-flow

@rensmere any insight on this? Does it need to be implemented?

**Comment by rensmere** [comment]
Streamflow does not need to be implemented.

On Oct 25, 2017, at 9:25 AM, Lance Albertson <notifications@github.com<mailto:notifications@github.com>> wrote:


I discovered that we haven't implemented Stream Flow data into the application. There seems to be about 62 data entries for this data type like this one: http://drupal.streamwebs.org/data/stream-flow/west-olalla-creek/05-30-2017. I'm not sure whether this was intentional or on the to do list. Here is what the input form looks like: http://drupal.streamwebs.org/node/add/data-stream-flow

@rensmere<https://github.com/rensmere> any insight on this? Does it need to be implemented?
