### ISSUE TITLE
Water quality data sheets should update input value to 0 if no option is present

### ISSUE THREAD

**Issue by NathanTan** [osuosl/streamwebs#593]
Manual or Vernier must be selected, or else the value should be reset to 0 for that field.

**Comment by hertelc** [comment]
@NathanTan is there a way to have the data be "blank" if there isn't any option selected?  Cait made a good point this morning in that there is a difference between not putting in data and the data actually being zero.  In the case of the graphs we don't want to graph a point that wasn't entered vs. one that actually was a zero.

**Comment by hertelc** [comment]
@CarvellWakeman in case Nathan is not in this morning.

**Comment by hertelc** [comment]
Actually... the value should be "blank" if the "none" is still selected, not zero.

**Comment by CarvellWakeman** [comment]
On this form, when a tool selection of None is supplied, it is still possible to enter a number. I'm making the assumption here that this is valid, because you can have no tool (none), but have a temperature that was guessed.

Proposed acceptance criteria
- Under the data sample section, the four samples for the six data types (water temp, air temp, dissolved O2, PH, Turbidity, and salinity) should default to blank (instead of zero)
- Those same six data types should allow empty input for the form validation
- Those same six data types should not reset data when the Tool selection is changed
- Any tool option is allowed for any value entered (including blank)
- Zero values must be recorded AS zero, instead of blank (IE: On the view page, zeros should display)

**Comment by hertelc** [comment]
Zach,  If none is selected there should be no result entered and the value will be blanked out if entered.  There is a sentence at the top of the form mentioning this.

CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu

**Comment by CarvellWakeman** [comment]
Also closes #608
