### ISSUE TITLE
Histograms not working

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#660]
Tested via dev with 'jerryp/fix_water_points' branch.

The graph for Water Quality is looking better. But when I select the option to view the histogram for a point, the graph is not showing up.

Compare between dev and prod:
http://streamwebs-dev.osuosl.org:8000/sites/wenaha-river/water/air_temperature/2016-09-28/
https://streamwebs.org/sites/wenaha-river/water/air_temperature/2016-09-28/

**Comment by JerryPeng0112** [comment]
@hertelc 
I've taken a look at the pages from both dev and prod. It looks like both Wenaha-river sites uses the old water quality graphing code. However, the one on prod has more water quality data sheets, thats why for the following 2 links for water quality graph, the dev has no graph and prod has some data on graph.
http://streamwebs-dev.osuosl.org:8000/sites/wenaha-river/water/
https://streamwebs.org/sites/wenaha-river/water/
Because the dev does not have data on water quality, the histogram naturally does not have data. In normal usage, the user shouldn't be able to go to the histogram page, because the water quality graph does not have graphs, which means no data points to select on, which means no way to access that invalid histogram page unless specifically typing out the url that way.

I will test this theory with this new water quality graph code asap.

**Comment by hertelc** [comment]
@JerryPeng0112 unless you updated Dev, it likely has the old Water Quality code.  I had Lance switch which branch was deployed many times today.

**Comment by JerryPeng0112** [comment]
@hertelc 
This is an issue on my end as well, will look into it asap. The theory above is not corerct.

**Comment by hertelc** [comment]
@JerryPeng0112 this looks good, please merge.  Please leave this issue open until we check it off on staging.

**Comment by hertelc** [comment]
Looks good in staging.  Closing issue.
